version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html  # Destination directory on EC2 or specific directory on Lambda
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
